version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=sqlite:///./requests.db
      - API_KEY=supersecretkey
      - KAFKA_BOOTSTRAP=broker:9092
  redis:
    image: redis:alpine
  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  zookeeper:
    image: bitnami/zookeeper:latest
